### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by WROG208** [W5DMH/Allstar-Announcer#1]
You forgot to add where to store the script. Im guessing /usr/local/sbin/ 
Also once the file is transferred to the Pi you also have to change its permissions to be able to run.

**Comment by W5DMH** [comment]
It doesn't care where it is installed, it can run pretty much anywhere. 
That said I assumed most would put it in /usr/local/sbin

**Comment by WROG208** [comment]
a lot of users don't know much or are afraid of dealing with this stuff unless they have a DIY. If not you will get 20 questions every day on how to use it, where to set it, and so on.
