### ISSUE TITLE
gTTS missing in the gmrslive image

### ISSUE THREAD

**Issue by WROG208** [W5DMH/Allstar-Announcer#2]
If this is run in the gmrslive image gTTS is not installed in such image. Might be on the all-star image don't know. If it has to be installed run this Command to install from BASH Shell.

`python3 -m pip install gTTS`

**Comment by W5DMH** [comment]
> If this is run in the gmrslive image gTTS is not installed in such image. Might be on the all-star image don't know. If it has to be installed run this Command to install from BASH Shell.
> 
> `python3 -m pip install gTTS`

Added to instructions
